language: python
python:
 - "2.7"

install:
 - >
  sed -e 's/^SECRET_KEY = .*$/SECRET_KEY = "travis-secret-key"/'
  filesharing/filesharing/local_settings.py.template
  >filesharing/filesharing/local_settings.py
 - pip install -r requirements.txt

script: filesharing/manage.py test filesharing/
